services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    ports:
      - ${FASTAPI_PORT}:8000
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASS}
      - DB_NAME=${POSTGRES_NAME}
    volumes:
      - ../src:/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  alembic:
    build:
      context: ..
      dockerfile: docker/alembic/Dockerfile
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASS}
      - DB_NAME=${POSTGRES_NAME}
    # command: tail -f /dev/null

  postgresql:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ./postgresql/data:/var/lib/postgresql
    restart: always
