FROM python:3
ENV PYTHONUNBUFFERED 1


# Create code source code folder
RUN mkdir /code
WORKDIR /code


# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip


# Install python packet
COPY requirements.txt /code
RUN pip install -r requirements.txt
